export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_CURRENCY = 'ACTION_CURRENCY';
export const ACTION_EXPENSES = 'ACTION_EXPENSES';
export const ACTION_ERASE = 'ACTION_ERASE';
export const ACTION_ID_EDIT = 'ACTION_ID_EDIT';
export const ACTION_EDITOR = 'ACTION_EDITOR';
